### ISSUE TITLE
Create a build script for HSLayers for npm package publication, library minification, etc.

### ISSUE THREAD

**Issue by SLeitgeb** [hslayers/hslayers-ng#136]

**Comment by SLeitgeb** [comment]
Also try including `babel` or other transpiler from ES6.

**Comment by raitisbe** [comment]
npm can be published with
`release-it `

**Comment by raitisbe** [comment]
Bundling process is described in https://github.com/hslayers/hslayers-ng/wiki/Bundling but it requires app.js project file first. Only hslayers isnt bundled yet, I dont know at the moment what to do with html templates, since they are standalone files and not part some bundle. Maybe webpack solves that better?

**Comment by raitisbe** [comment]
`npm run build`
and htmls + css will be bundled too
