### ISSUE TITLE
Angular material should not load for non material templates

### ISSUE THREAD

**Issue by ChcJohnie** [hslayers/hslayers-ng#138]
Material and its services is currently imported with default layout controller, which means extra 400kb for non-material app.
Maybe standalone template+controller for each of material/non-material/mobile app???

**Comment by raitisbe** [comment]
definately

**Comment by ChcJohnie** [comment]
Also Glyphicon font is currently loading everywhere (bulky 250kb).
When I move it from hslayers.html to layout.html font file doesnt load (only css file loads).
Another solution would be to use only halflings glyphs included in bootstrap anyway and get rid of extra dependency

**Comment by raitisbe** [comment]
Icon sets are not included into bootstrap anymore in the latest version. 
We are using now whhg icons. I moved css inclusion to layout.html and also added ng-if to be able to turn off loading them, because in webpack setup where css is imported somewhere else (app.js), they would be included twice otherwise.
We still have "glyphicon" class on elements for backwards compatibility in some applications, but I think it should be safe to remove it as time goes on.
