### ISSUE TITLE
Add attribute in Info panel returns error

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1626]
When adding new attribute and then specifying its value, error is thrown as the attribute does't exist yet.

**Comment by DailisLangovskis** [comment]
@fzadrazil Can You provide a scenario, because I tested this inside HUB and couldn't produce such an error.

**Comment by FilipLeitner** [comment]
![image](https://user-images.githubusercontent.com/44566616/109503107-2210a300-7a9a-11eb-80e7-9a5966faf10d.png)

**Comment by FilipLeitner** [comment]
Create draw layer - add feature - try adding new attribute

**Comment by FilipLeitner** [comment]
From what I understood.. the [docs](http://docs.opengeospatial.org/is/04-094r1/04-094r1.html#74) says its only possible to update existing properties via WFS transaction request. 

_An <Update> element contains one or more <Property>elements that specify the name and replacement value for a property that belongs to the feature type specified using the mandatory typeName attribute._

So we will probably have to create new feature and delete the old one in order to 'add a property'
