### ISSUE TITLE
Cannot read property 'getSource' of null

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#1954]
![err](https://user-images.githubusercontent.com/46564459/123541176-cc988a00-d74b-11eb-9e2d-00ddac03bd5a.png)
When loading layer from layman inside the draw toolbar!

**Comment by fzadrazil** [comment]
It happens even when trying to create a new drawing layer.

**Comment by FilipLeitner** [comment]
On current develop and without an error I was able to :
- create new drawing layer without an error (saved to layman succesfully also)
- load already existing layer from layman
- edit loaded layer (add/delete polygon feature)

**Comment by fzadrazil** [comment]
It happens when you are not logged in, open draw panel, click on New drawing layer, Login from the dialog and try to create new layer. It crashes on this line as this.selectedLayer is null
https://github.com/hslayers/hslayers-ng/blob/c91cae1e30ddd23c64dedef4645969a541f96380/projects/hslayers/src/components/draw/draw.service.ts#L410
