### ISSUE TITLE
Prefix bootstrap and styles

### ISSUE THREAD

**Issue by bvj** [hslayers/hslayers-ng#197]
To avoid interaction with cms or similar systems using bootstrap too.

**Comment by raitisbe** [comment]
Can you give an example?

**Comment by bvj** [comment]
https://datahub.lesprojekt.cz/map

**Comment by raitisbe** [comment]
Now the hslayers layout is contained in <div id="page-wrapper" class="bootstrap-iso">
We need to generate a special bootstrap.isolated.css file based on the original bootstrap.css where every selector is prefixed with .bootstrap-iso
This can be done with scripts/bootstrap-isolate.js script, which can be run also through 
```npm explore hslayers-ng -- npm run isolate-bootstrap``` if hslayers-ng is dependency of your app or ```npm run isolate-bootstrap``` if you have cloned hslayers-ng repo directly.
In app.js we have to set config: ```{useIsolatedBootstrap: true}``` to tell hslayers to use this isolated version of bootstrap, otherwise we force everyone the generate this css file which is unnecessary in most cases,
