### ISSUE TITLE
Query info panel always displays top-most layer title

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2617]
# Bug

**Describe the bug**
When a layer is queried, Info panel displays top-most layer title instead of active layer title. The properties displayed are correct.

**To Reproduce**
1. Add two overlapping layers
2. Hide one of them
3. Click on some feature in the active layer
4. See incorrect title (if this layer was not top-most, otherwise the title is correct)

**Expected behavior**
Correct title shall be displayed.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/5598693/152007262-b780f82c-c7cd-4092-9808-f52b8dec0ee4.png)
![obrazek](https://user-images.githubusercontent.com/5598693/152008135-efef3b09-51c9-4dad-8a89-718fda2df24b.png)

**Additional context**
Tested under 7.0.4

**Comment by jmacura** [comment]
Also affects the popUp window.
![obrazek](https://user-images.githubusercontent.com/5598693/152063627-864e7256-6f59-464b-9db1-e74e9d13bbc4.png)
The layer displayed is turned off at the moment.
![obrazek](https://user-images.githubusercontent.com/5598693/152063734-f7b9ece5-e3fb-40f1-aa4d-84db119589bb.png)

**Comment by raitisbe** [comment]
I tested in release-7.x branch with the test-app which includes two overlapping vector layers "Polygons"  and "Polygons with display f-n". Didn't observe anything out of order. 
![image](https://user-images.githubusercontent.com/395514/152072140-2311fdb5-339a-4a5a-96ec-d08314afa349.png)
![image](https://user-images.githubusercontent.com/395514/152072165-6bc3d9cf-bb45-42fa-aaa4-29cf104f7612.png)

You might wanna put a breakpoint in query-vector.service.ts
```
filter: function (feature, layer) {
        if (layer === null) {
          return;
        }
        if (getQueryable(layer) === false) {
          return false;
        } else {
          return true;
        }
      },
```
For me it only triggered on the visible layer. If it happens on invisible ones, we might get closer to the culprit, since we dont filter for visibility here. 

Do the feature IDs match for both layers? In that case the problem might be the caching mechanism here https://github.com/hslayers/hslayers-ng/blob/release-7.x/projects/hslayers/src/components/map/map.service.ts#L180 which maps feature ID with layer object.

**Comment by raitisbe** [comment]
Bug confirmed. Needed to set id for features in 2 layers to equal value (id outside properties in geojson)
