### ISSUE TITLE
Whole map gets grayscaled instead of just one base layer

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2656]
# Bug

**Describe the bug**
When a "grayscale" option is selected on a base layer, a whole map gets grayscaled instead of just that layer. The bug is resolved immediately after you move the map.

**To Reproduce**
1. Go to LayerManager either in panel or in a gallery
2. Click on 'Grayscale'
4. See the whole map turn gray

**Expected behavior**
Only the base layer for which the "grayscale" parameter was set, should be gray, other layers should be intouched.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/5598693/153085933-b8af07a2-57a2-4337-8b46-f9f16bc55a92.png)
![obrazek](https://user-images.githubusercontent.com/5598693/153085971-40cef7fa-31a9-44da-a9b8-83e48d5127b7.png)
![obrazek](https://user-images.githubusercontent.com/5598693/153085996-eeb7f696-56a8-4d9d-9aba-95e85715120d.png)

**Additional context**
.

**Comment by DailisLangovskis** [comment]
@jmacura Hmm, i tried it, without moving the map, and i cannot replicate it!

**Comment by FilipLeitner** [comment]
There was some kind of problem with identifying the proper element to on which we can apply filter. Maybe something has changed since. Will take a look

**Comment by raitisbe** [comment]
I remember that sometimes OL draws many layers on the same canvas, sometimes a separate canvas is create for each or groups of layers. Might depend on projection and type of layer.

**Comment by FilipLeitner** [comment]
Once again there is an ol extension or rather two in this case
- [canvas filters](https://viglino.github.io/ol-ext/examples/filter/map.filter.canvasfilter.html?lon=3.003349&lat=50.652784&z=11)
-  [color filters](https://viglino.github.io/ol-ext/examples/filter/map.filter.colorize.html?lon=2.022926&lat=50.261913&z=8)

Tried experimenting with [canvas context filters](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData) but without any succes. 
![image](https://user-images.githubusercontent.com/44566616/153185184-d0fd1996-238b-4503-8d9c-0ddd9b65ee13.png)

Filter property is not  changing for some reason. [Can I use](https://caniuse.com/mdn-api_canvasrenderingcontext2d_filter)


With color filters I was a bit more 'succesfull'. Was able to apply grayscale color filter but doing so (used a base map) every other layer dissapear. Probably because they are in the same canvas and fillRect() method call.
![image](https://user-images.githubusercontent.com/44566616/153194810-61e36e4a-98ab-4fb8-9eeb-26239752f48b.png)

![image](https://user-images.githubusercontent.com/44566616/153196213-7c98cf27-070b-4748-b2c1-315f65c89271.png)

**Comment by jmacura** [comment]
Oh, I can see now. It only happens in Firefox. I have tried M$ Edge and only the background got grayed.
