### ISSUE TITLE
Sidebar content off the screen

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3648]
# Bug

**Describe the bug**
Content of panels in the sidebar overflows from the screen when there is a slider present

**To Reproduce**
1. Go to any panel which has a lot of content. E.g. 'Layermanager' or 'Styler'
4. See how the content on the right hand side is cropped by the window edge

**Expected behavior**
Either the panel shall enlarge by the size of the slider or the content must shrink so it does not overflow. Or reserve the place on the side of the panel since the beginning. Displaying another slider in the bottom is not an option.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/208198624-bc5ff93d-f67c-478b-831d-09bbc2515048.png)
![image](https://user-images.githubusercontent.com/5598693/208198415-b12da7bc-cb22-45a1-81f7-cc70ec2212f4.png)
![image](https://user-images.githubusercontent.com/5598693/208198477-278e3291-35da-485c-9c4b-ec1ee05b4aa0.png)

**Additional context**
I observed a change in b6f460f5086d387c8b060aa8e19aaff4cd576321 on this line https://github.com/hslayers/hslayers-ng/blob/b6f460f5086d387c8b060aa8e19aaff4cd576321/projects/hslayers/src/components/styles/symbolizers/fill-symbolizer/fill-symbolizer.component.html#L27 which seemed to deal with that exact issue at one particular place.

**Comment by raitisbe** [comment]
This seems to be browser/OS specific and comes from the fact that we are forcing the body element to have margin: 0; That for the main body slider, which is set in index.html so we hslayers doesnt care about that.

A different beast is the separate slider for `.hs-panelplace ` element. Since not all panels are filling the complete height, it would not make sense to have a margin-right applied to all of them. I would go with the application of me-1 or me-2  to the tricky controls, such as the cog icon in layer manager or filter/scale/+ buttons in styler. Also buttons in panel headers seem to need margins.

**Comment by FilipLeitner** [comment]
I remember doing some changes for symbolizer indentation in #3584. Will rebase and check if its solved already or need some work.

**Comment by raitisbe** [comment]
I did some experimentation in my branch, but not 100% happy with the result. Its a struggle to align betweeen chrome and firefox, since chrome automatically takes into account the scrollbars and margin isn't even necessary and in the results its padded too much. On firefox its seems to be too little on the other hand. 
![image](https://user-images.githubusercontent.com/395514/208420932-bb731732-e1a0-485d-a23f-855663ef641d.png)

**Comment by raitisbe** [comment]
In case your result is better @FilipLeitner lets go with yours

**Comment by FilipLeitner** [comment]
Unfortunately not,  was bit something different at last. I probably I agree with on this 
> I would go with the application of me-1 or me-2

**Comment by FilipLeitner** [comment]
This seems to be working, for now at least:
https://sass-lang.com/documentation/breaking-changes/moz-document

```
  @-moz-document url-prefix() {
    & .hs-panelplace {
      padding-right: 0.25rem;
    }
  }
  ```

**Comment by jmacura** [comment]
It is slightly better now, but not perfect for sure.
![image](https://user-images.githubusercontent.com/5598693/210365857-530d1423-d176-4c21-aa80-2ef90b51dc18.png)

**Comment by raitisbe** [comment]
Is it on firefox?

**Comment by jmacura** [comment]
> Is it on firefox?


Indeed.

**Comment by raitisbe** [comment]
How does it look 9n chrome?

**Comment by jmacura** [comment]
In Chrome/Edge it is fine, as it was mentioned already.
![image](https://user-images.githubusercontent.com/5598693/210387753-488e1b14-3e95-41d6-9b78-fe5bb04eb650.png)

**Comment by raitisbe** [comment]
It looks even too far away from the border. So I guess the current state is
the best middleground which to strike without detecting browsers and
dynamically adjusting offset.
