### ISSUE TITLE
Add support to load external data layer from file

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#383]
Currently, it is possible to add a new custom layer (GeoJSON or KML) from remote URL.
![issue-addd_local_file_upload_support](https://user-images.githubusercontent.com/5598693/69144133-e8956d80-0aca-11ea-8988-077ca8d033e2.png)

We need to also allow an upload of the file from the user's filesystem.

Question is, how to handle that file afterwards - whether it will only be loaded in the client-site and discarded when the user leaves the HSL window or if it will be uploaded to our servers and saved temporarily/permanently in user's profile/in project's profile...?

**Comment by raitisbe** [comment]
Currently there is a dragdrop possibility to "upload" file on client side. If it is a vector file, then the features can be serialized and stored to layman or status manager i.e. uploaded to server as geojson. For Layman its possible to store separate layers and later composition. Statusmanager stores only the whole composition  - layers + map viewport. 

We need to also have upload button in the panel from the image, because users don't know about this drag&drop possibility.

**Comment by raitisbe** [comment]
Refs issue #209

**Comment by raitisbe** [comment]
Saving to layman and status manager is done in save-map component

**Comment by raitisbe** [comment]
Time: 2h
