### ISSUE TITLE
Prioritize internal requests

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#4058]
# Bug

**Describe the bug**
In case user adds external WMS that is not optimized and has very long response times, it may cause other requests from hslayers to fail (eg. request for Layman layers or Micka CSW). The flawed WMS issues a request for each tile and the Layman request is not served before the WMS responses. That leads to a failed Layman request because of timeout.

**To Reproduce**
1. Go to [AgriHub](https://www.agrihub.cz/mapy/)
2. Open map composition named "VUV záplavová území"
3. Monitor the network traffic.

**Expected behavior**
Internal server requests should have the priority and be called before any requests for map content.

**Comment by FilipLeitner** [comment]
I have tried playing around a bit with suppressing number of concurrent layer loading requests. Not so straightforward as getMap requests are issued internally by bowser when src is set on img but it seems like its possible.
Heres a my try on non tiled WMS and ArcGISRest layers
https://github.com/hslayers/hslayers-ng/compare/develop...issue-4058

We can add timeout to queue definition `const que = this.hsQueuesService.ensureQueue('imageLoad', 4, TIMEOUT);` After this timeout, it will issue another request if there are still some pending.
`4` is the number of max concurrent requests. Chose 4 as the browser should be able to handle 6 at a time so it would be something like 4 on layers, 1 for capabilities and 1 for the rest.  
In combination with a timeout (which can be set and modified for each individual request) we might fine-tune the behaviour of the queue for example so that the first request would have some shorter timeout necessary only for other tasks such as  Layman layers or Micka CSW to complete ...this would free one more request 'slot' for layers after

**Comment by fzadrazil** [comment]
It seems much better and works nicely even on tiled WMS and my wide screen (15 concurrent WMS requests). So I would follow this way.
