### ISSUE TITLE
Lazy loading of built js files breaks simple apps

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#664]
Simple apps like [simple map example](https://github.com/hslayers/examples/tree/master/simple-map) and [P4A website map](https://github.com/jmacura/p4a-website-map) loads JS bundles improperly – searching in a root (index.html's) directory instead of the same directory as the hslayers-ng.main.js file. See screenshot below.

![image](https://user-images.githubusercontent.com/5598693/82767617-33e95980-9e29-11ea-8843-674a9cb85c30.png)

**Comment by MrToxy** [comment]
I keep seeing references to https://github.com/hslayers/hslayers-ng/pull/665 but no actual explanation or example on how to set it up.
Is this included by default with webpack?
What options does it take in?
What do we need to configure?

@raitisbe since you're the one referencing that commit on multiple issues of this kind, could you please provide more details?
